In [1]:
# 學生進度較慢，03/24/2021 上傳作業新作業發現自 Day001 之後的課程大綱都有異動
# 且近日舊作業也有被清掉狀況，又發現 Day001 作業有新題目，故先更新第一篇作業
# 其他先上傳舊檔，日後複習後再重新更新 ~~
#1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。
import numpy as np

A=np.arange(0,21)
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [2]:
#2.呈上題，將以上數列取出偶數。
B=A[::2]
print(B)

[ 0  2  4  6  8 10 12 14 16 18 20]


In [3]:
#3.呈 1 題，將數列取出 3 的倍數。
C=A[3::3]
print(C)

[ 3  6  9 12 15 18]


In [4]:
# 4. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？
a = np.random.randint(10, size=10) 
print('a list: ', list(a))
print('a tolist: ', a.tolist())

b = np.random.randint(10, size=10).reshape(5,2)
print('\nb list: ', list(b))
print('b tolist: ', b.tolist())

# 答案：
# list()只會把第一層的元素轉換成 List，多層的話只有第一層會轉換。
# tolist()才能達成多層的型態轉換。

a list:  [9, 7, 3, 6, 0, 1, 4, 5, 6, 8]
a tolist:  [9, 7, 3, 6, 0, 1, 4, 5, 6, 8]

b list:  [array([5, 9]), array([1, 6]), array([9, 8]), array([7, 7]), array([7, 5])]
b tolist:  [[5, 9], [1, 6], [9, 8], [7, 7], [7, 5]]


In [5]:
# 5. 請試著在程式中印出以下三個 NdArray 的屬性？
#   （屬性：ndim、shape、size、dtype、itemsize、length、type）
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 

print('a : ',a)
print('a ndim: ',a.ndim)
print('a shape: ',a.shape)
print('a size: ',a.size)
print('a dtype: ',a.dtype)
print('a itemsize: ',a.itemsize)
print('a length: ',len(a))
print('a type: ',type(a))

print('\nb : ',b)
print('b ndim: ',b.ndim)
print('b shape: ',b.shape)
print('b size: ',b.size)
print('b dtype: ',b.dtype)
print('b itemsize: ',b.itemsize)
print('b length: ',len(b))
print('b type: ',type(b))


print('\nc : ',c)
print('c ndim: ',c.ndim)
print('c shape: ',c.shape)
print('c size: ',c.size)
print('c dtype: ',c.dtype)
print('c itemsize: ',c.itemsize)
print('c length: ',len(c))
print('c type: ',type(c))

a :  [1 6 4 3 2 8]
a ndim:  1
a shape:  (6,)
a size:  6
a dtype:  int32
a itemsize:  4
a length:  6
a type:  <class 'numpy.ndarray'>

b :  [[6 8 6 6]
 [8 1 5 6]
 [2 4 2 0]]
b ndim:  2
b shape:  (3, 4)
b size:  12
b dtype:  int32
b itemsize:  4
b length:  3
b type:  <class 'numpy.ndarray'>

c :  [[[0 5]
  [5 6]
  [8 8]]

 [[7 3]
  [2 0]
  [2 3]]]
c ndim:  3
c shape:  (2, 3, 2)
c size:  12
c dtype:  int32
c itemsize:  4
c length:  2
c type:  <class 'numpy.ndarray'>


In [6]:
# 6. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。
a = np.random.randint(10, size=6) 
print(a.tolist())
print(list(a))

b = np.random.randint(10, size=(3,4)) 
print(b.tolist())
print(list(b))

c = np.random.randint(10, size=(2,3,2)) 
print(c.tolist())
print(list(c))

# 此區看講解作答
def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    return [tolist(obj) for obj in iterable]

print('利用 list(a) 實踐 a.tolist() 的效果:', tolist(a))
print('利用 list(b) 實踐 b.tolist() 的效果:', tolist(b))
print('利用 list(c) 實踐 c.tolist() 的效果:', tolist(c))

[6, 4, 8, 0, 9, 5]
[6, 4, 8, 0, 9, 5]
[[7, 0, 7, 8], [7, 7, 4, 6], [1, 1, 9, 9]]
[array([7, 0, 7, 8]), array([7, 7, 4, 6]), array([1, 1, 9, 9])]
[[[5, 7], [4, 4], [7, 6]], [[9, 7], [6, 6], [5, 0]]]
[array([[5, 7],
       [4, 4],
       [7, 6]]), array([[9, 7],
       [6, 6],
       [5, 0]])]
利用 list(a) 實踐 a.tolist() 的效果: [6, 4, 8, 0, 9, 5]
利用 list(b) 實踐 b.tolist() 的效果: [[7, 0, 7, 8], [7, 7, 4, 6], [1, 1, 9, 9]]
利用 list(c) 實踐 c.tolist() 的效果: [[[5, 7], [4, 4], [7, 6]], [[9, 7], [6, 6], [5, 0]]]
