In [1]:
import numpy as np
#題目: 1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
array1 = np.array([[10, 8], [3, 5]])
# 計算反矩陣
arr2 = np.linalg.inv(array1)
print('反矩陣：\n',arr2)
# 計算反矩陣
# 反矩陣乘上原矩陣
arr3 = array1 @ arr2
print('反矩陣乘上原矩陣：\n',arr3)
#答案:
# 反矩陣：
# [[ 0.19230769 -0.30769231]
#  [-0.11538462  0.38461538]]
# 反矩陣乘上原矩陣：
# [[1. 0.]
# [0. 1.]]
# 反矩陣乘上原矩陣其對角線值為1，故「是」單位矩陣。

反矩陣：
 [[ 0.19230769 -0.30769231]
 [-0.11538462  0.38461538]]
反矩陣乘上原矩陣：
 [[1. 0.]
 [0. 1.]]


In [2]:
#題目: 2. 運用上列array計算特徵值、特徵向量?
w, v = np.linalg.eig(array1)
print('特徵值：\n',w)
print('特徵向量：\n',v)
#答案:
# 特徵值：
# [13.  2.]
# 特徵向量：
# [[ 0.93632918 -0.70710678]
# [ 0.35112344  0.70710678]]

特徵值：
 [13.  2.]
特徵向量：
 [[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]]


In [3]:
#題目: 3. 運用上列array計算SVD?
u, s, vh = np.linalg.svd(array1)
print('分解得到矩陣的形狀：\n',u.shape,s.shape,vh.shape)
#答案:
# 分解得到矩陣的形狀：
#  (2, 2) (2,) (2, 2)

分解得到矩陣的形狀：
 (2, 2) (2,) (2, 2)
