In [1]:
import numpy as np
#題目: 將下兩列array存成npz檔
array1 = np.array(range(30))
array2 = np.array([2,3,5])
with open('multi_array.npz', 'wb') as f:
    np.savez(f, a1=array1, a2=array2)

In [2]:
#題目: 2. 讀取剛剛的npz檔，加入下列array一起存成新的npz檔
#      由於沒有下列 array 的題目, 故自定義 array3
# array3 = np.array([30,40,50,60]) 解答有陣列, 修正前
# with open('multi_array3.npz', 'wb') as f: 修正前
#    np.savez(f, a1=array1, a2=array2, a3=array3) 修正前
# 使用 load 函式, 可以不用 with open 做法
load_array = np.load('multi_array.npz')
array3 = np.array([[4,5,6],[1,2,3]])
np.savez('multi_array3.npz',load_array['a1'],load_array['a2'],array3)

In [3]:
# 練習讀取
npzfile3 = np.load('multi_array3.npz')
print(npzfile3['arr_0'])
print(npzfile3['arr_1'])
print(npzfile3['arr_2'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]
[[4 5 6]
 [1 2 3]]
